bapp/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include
from bapp.views import *

appname = 'bapp'

urlpatterns = [

    path('', views.dash, name='homeview'),

    # Purchase Service
    # path('addbook', views.addbook, name='addbook'),
    # path('planselection', views.planselection, name='planselection'),
    # path('planconfirmation', views.planconfirmation, name='planconfirmation'),
    # path('orderconfirmation', views.orderconfirmation, name='orderconfirmation'),

    # cancel order - order will be marked as cancelled and refund request will be initiated
    path('cancel_activeorder', views.cancel_activeorder, name='cancel_activeorder'),
    path('refund', views.refund, name='refund'),
    path('refund_confirmation', views.refund_confirmation, name='refund_confirmation'),

    # General
    path('orderhistory', views.orderhistory, name='orderhistory'),
    path('vieworder', views.vieworder, name='vieworder'),
    path('cancel', views.cancelorder, name='cancel'),

    # bookview
    path('booklist', views.booklist, name='booklist'),
    path('viewbook/<slug:slug>/', views.viewbook, name='viewbook'),
    # to add general details of a book
    path('addbook/', views.addbook, name='addbook'),
    path('addchapter/<slug:slug>/', views.addchapter, name='addchapter'),
    path('editbook/<slug:slug>/', views.editbook, name='editbook'),
    path('changeorder/', views.changeorder, name='changeorder'),
    # to drag and drop files
    path('upload/', views.file_upload_view, name='upload-view'),
    # services
    path('myservices', views.myservices, name='myservices'),
    path('servicelist', views.servicelist, name='servicelist'),
    path('services/<slug:slug>/', views.viewservice, name='viewservice'),
    path('serviceconfirmation/', views.serviceconfirmation, name='serviceconfirmation'),
    path('serviceordersuccess/', views.serviceordersuccess, name='serviceordersuccess'),

    # admin

    # login

    path('login/', views.login_view, name='login'),
    path('auth/', views.log_usr, name='auth'),
    path('logout/', views.logoutUser, name="logout"),

]

bookapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('bapp.urls', 'bapp'), namespace='bapp')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from ckeditor.widgets import CKEditorWidget
from django.forms import ModelForm
from .models import  *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email',  'password1', 'password2']

class UpdatePassword(UserCreationForm):
    class Meta:
        model = User
        fields = ['password1', 'password2']

# class ProfileForm(ModelForm):
#     class Meta:
#         model = Profile
#         fields = '__all__'
#         exclude = ['user']


# class UpdateCouponForm(ModelForm):
#     class Meta:
#         model = Book_list
        
#         fields = ['book_title', 'book_code', 'book_img', 'book_description',
#                     'subscription_status', 'subscription_id', 'publishing_status', 'publishing_status']

# class UpdatePropertyForm(ModelForm):
#     class Meta:
#         model = Book_list
        
#         fields = ['Book_name', 'Book_headline', 'Book_image', 'Book_description',
#                     'Book_special_description', 'Book_link', 'publishing_status']
        

bapp/views.py
from bapp.models import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from .forms import *


def login_view(request):
    form = CreateUserForm()
    if request.user.is_authenticated:
        return redirect('bapp:dashboard_usr')
    else:
        if request.method == 'POST':
            if request.POST.get('submit') == 'sign_in':
                email = request.POST.get('email')
                password = request.POST.get('password')

                user = authenticate(request, username=email, password=password)
                if user:
                    if user.is_active:
                        print(request.user)
                        login(request, user)
                        return redirect('bapp:homeview')

                    else:
                        messages.info(request, 'Verify your mail to get fullaccess !')
                        return redirect('bapp:login')
                else:
                    messages.error(request, 'Email or Password are incorrect')
                    return redirect('bapp:login')

            else:
                return render(request, 'bapp/user/login.html')
        else:
            return render(request, 'bapp/user/login.html')


# 10. Signup


def log_usr(request):
    form = CreateUserForm()
    if request.user.is_authenticated:
        return redirect('bapp:homeview')
    else:
        if request.method == 'POST':
            if request.POST.get('submit') == 'sign_in':
                email = request.POST.get('email')
                password = request.POST.get('password')

                user = authenticate(request, username=email, password=password)
                if user:
                    if user.is_active:
                        print(request.user)
                        login(request, user)
                        return redirect('bapp:dashboard_usr')

                    else:
                        messages.info(request, 'Verify your mail to get fullaccess !')
                        return redirect('bapp:login')
                else:
                    messages.error(request, 'Email or Password are incorrect')
                    return redirect('bapp:auth')


            else:
                messages.error(request, "Something went wrong, Please try again!")
                return redirect("bapp:auth")

        context = {
            'form': form,

        }
        return render(request, 'bapp/user/authentication-signup.html', context)


def logoutUser(request):
    logout(request)
    return redirect('bapp:login')


@login_required
def viewbook(request, slug=None):
    book_instance = get_object_or_404(book_list, slug=slug)
    current_user = request.user
    chapters = chapter.objects.filter(book=book_instance).order_by('order')
    images = img_addon.objects.filter(book=book_instance)

    context = {
        'book': book_instance,
        'chapters': chapters,
        'images': images,
        'user': current_user,
        'slug': slug
    }
    return render(request, 'bapp/user/bookview.html', context)


def addchapter(request, slug):
    Chapter = chapter.objects.all()
    if request.POST:
        chapter_title = request.POST.get('chapter_title')
        mydescription = request.POST.get('mydescription')
        Chapter = chapter()
        Chapter.chapter_title = chapter_title
        Chapter.chapter_body = mydescription
        Chapter.book = book_list.objects.get(slug=slug)
        Chapter.save()
    return render(request, 'bapp/user/bookview.html', {'Chapter': Chapter, 'slug': slug})


def editbook(request, slug):
    if request.POST:
        book_title = request.POST.get('book_title')
        book_description = request.POST.get('book_description')
        publishing_status = request.POST.get('publishing_status')
        subscription = request.POST.get('subscription')
        book = book_list.objects.get(slug=slug)
        book.book_title = book_title
        book.book_description = book_description
        book.publishing_status = publishing_status
        book.subscription_status = subscription
        book.save()
    return redirect('/')


def file_upload_view(request):
    import pdb
    pdb.set_trace()
    if request.POST:
        chapter_file = request.FILES.get('file')
        book_list.objects.create(upload=chapter_file)
    return HttpResponse('upload')


@login_required()
def dash(request):
    current_user = request.user
    book = book_list.objects.filter(book_owner=current_user)
    context = {
        'book': book,

    }

    return render(request, 'bapp/user/index.html', context)


def orderhistory(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/booklist.html', context)


def vieworder(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/booklist.html', context)


def cancelorder(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/booklist.html', context)


# when the subscription ended the book status should change to expired
def cancel_activeorder(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/booklist.html', context)


# order will be marked as cancelled -- particular book code will be marked as cancelled
def refund(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/booklist.html', context)


def refund_confirmation(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/booklist.html', context)


def booklist(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/booklist.html', context)


def addbook(request):
    book = book_list.objects.all()

    context = {
        'book': book,

    }

    return render(request, 'bapp/user/addbook.html', context)


def servicelist(request):
    service_list = services.objects.all()

    context = {
        'services': service_list,
    }
    return render(request, 'bapp/user/services.html', context)


def myservices(request, ):
    current_user = request.user
    user_name = User.objects.get(email=current_user.email)
    service_list = services.objects.filter(service_user=user_name)

    context = {
        'services': service_list,
    }
    return render(request, 'bapp/user/myservices.html', context)


def viewservice(request, slug=None):
    service_list = services.objects.all()
    service_instance = get_object_or_404(service_list, slug=slug)
    current_user = request.user

    context = {
        'Service': service_instance,
        'user': current_user
    }
    return render(request, 'bapp/user/viewservice.html', context)


def serviceconfirmation(request, slug=None):
    service_list = services.objects.all()
    service_instance = get_object_or_404(service_list, slug=slug)
    current_user = request.user

    context = {
        'service': service_instance,
        'user': current_user
    }
    return render(request, 'bapp/user/serviceconfirmation.html', context)


def serviceordersuccess(request, ):
    service_list = services.objects.all()
    current_user = request.user

    context = {
        'user': current_user
    }
    return render(request, 'bapp/user/serviceorderconfirmation.html', context)


def changeorder(request):
    chapter_list = request.GET.getlist('chapter_list[]')
    for counter, chapter_id in enumerate(chapter_list):
        chapter_obj = chapter.objects.get(id=chapter_id)
        chapter_obj.order = counter + 1
        chapter_obj.save()

    return JsonResponse(data={'message':'success'}, safe=True)

templates/bapp/user/authentication-signup.html
{% load static %}
<!doctype html>
<html lang="en">

	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!--favicon-->
		<link rel="icon" href="{% static 'admini/assets/images/favicon-32x32.png' %}" type="image/png" />
		<!-- loader-->
		<link href="{% static 'admini/assets/css/pace.min.css' %}" rel="stylesheet" />
		<script src="{% static 'admini/assets/js/pace.min.js' %}"></script>
		<!-- Bootstrap CSS -->
		<link href="{% static 'admini/assets/css/bootstrap.min.css' %}" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
		<link href="{% static 'admini/assets/css/app.css' %}" rel="stylesheet">
		<link href="{% static 'admini/assets/css/icons.css' %}" rel="stylesheet">
		<title>Book App  -write your book </title>
	</head>

<body class="bg-theme bg-theme1">
	<!--wrapper-->
	<div class="wrapper">
		<div class="d-flex align-items-center justify-content-center my-5 my-lg-0">
			<div class="container">
				<div class="row row-cols-1 row-cols-lg-2 row-cols-xl-2">
					<div class="col mx-auto">
						<div class="my-4 text-center">
							<img src="{% static 'admini/assets/images/logo-img.png' %}" width="180" alt="" />
						</div>
						<div class="card">
							<div class="card-body">
								<div class="border p-4 rounded">
									<div class="text-center">
										<h3 class="">Sign Up</h3>
										<p>Already have an account? <a href="{% url 'bapp:login' %}">Sign in here</a>
										</p>
									</div>
									<div style="color:rgb(240, 234, 234)">
										{% include 'bapp/user/alert.html' with messages=messages %}
					
									</div>
									<div class="login-separater text-center mb-4"> <span> SIGN UP WITH EMAIL</span>
										<hr/>
									</div>
									<div class="form-body">
										<form method="POST" class="row g-3">
											{% csrf_token %}

											<div class="col-12">
												<label for="inputEmailAddress" class="form-label">Email Address</label>
												<input name="email" type="email" class="form-control"  placeholder="example@user.com">
											</div>
											<div class="col-12">
												<label for="inputChoosePassword" class="form-label">Enter Password</label>
												<div class="input-group" id="show_hide_password">
													<input type="password" name="password1" class="form-control border-end-0"  placeholder="Enter Password"> <a href="javascript:;" class="input-group-text bg-transparent"><i class='bx bx-hide'></i></a>
												</div>
											</div>
											<div class="col-12">
												<label for="inputChoosePassword" class="form-label">Re Enter Password</label>
												<div class="input-group" id="show_hide_password">
													<input type="password" name="password2" class="form-control border-end-0"  placeholder="Enter Password"> <a href="javascript:;" class="input-group-text bg-transparent"><i class='bx bx-hide'></i></a>
												</div>
											</div>


											<div class="col-12">
												<div class="d-grid">
													<button type="submit" id="sign_up" name="submit" value="sign_up" class="btn btn-light"><i class='bx bx-user'></i>Sign up</button>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--end row-->
			</div>
		</div>
	</div>
	<!--end wrapper-->



	<!--plugins-->
	<script src="{% static 'admini/assets/js/jquery.min.js' %}"></script>


</body>

</html>

templates/bapp/user/booklist.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--favicon-->
	<link rel="icon" href="{% static 'admini/assets/images/favicon-32x32.png' %}" type="image/png" />
	<!--plugins-->
	<link href="{% static 'admini/assets/plugins/vectormap/jquery-jvectormap-2.0.2.css' %}" rel="stylesheet"/>
	<link href="{% static 'admini/assets/plugins/simplebar/css/simplebar.css' %}" rel="stylesheet" />
	<link href="{% static 'admini/assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet" />
	<link href="{% static 'admini/assets/plugins/metismenu/css/metisMenu.min.css' %}" rel="stylesheet" />
	<!-- loader-->
	<link href="{% static 'admini/assets/css/pace.min.css' %}" rel="stylesheet" />
	<script src="{% static 'admini/assets/js/pace.min.js' %}"></script>
	<!-- Bootstrap CSS -->
	<link href="{% static 'admini/assets/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
	<link href="{% static 'admini/assets/css/app.css' %}" rel="stylesheet">
	<link href="{% static 'admini/assets/css/icons.css' %}" rel="stylesheet">
	
	<title>Bookdash Book List </title>
</head>

<body class="bg-theme bg-theme1">
	<!--wrapper-->
	<div class="wrapper">
		<!--start header -->
	 {% include 'bapp/user/header.html' %}
		<!--end navigation-->
		<!--start page wrapper -->
		<div class="page-wrapper">
			<div class="page-content">

				<div class="card radius-10">
					<div class="card-body">
						<div class="d-flex align-items-center">
							<div>
								<h5 class="mb-0">Your Book List  </h5>
							</div>
							<div class="font-22 ms-auto"><i class="bx bx-dots-horizontal-rounded"></i>
							</div>
						</div>
						<hr>
						<div class="table-responsive">
							<table class="table align-middle mb-0">
								<thead class="table-light">
									<tr>
										<th>ID</th>
										<th>Book Title</th>
										<th>Book Cover</th>
										<th>Code</th>
										<th>Date</th>
										<th>Status</th>
										<th>Action</th>
						
									</tr>
								</thead>
								{% for i in book %}
								<tbody>
									
									<tr>
										<td>{{i.counter}}</td>
										<td>
											<div class="d-flex align-items-center">
											 <a href="{% url 'bapp:viewbook' i.slug %}" target="_blank" rel="noopener noreferrer">
												<div class="ms-2">
													<h6 class="mb-1 font-14">{{i.book_title}}</h6>
												</div>
											 </a>
											</div>
										</td>
										<td>	<div class="recent-product-img">
											<img src="{{i.book_img.url}}" alt="">
										</div></td>
										<td>{{i.book_code}}
											 		
										</td>
										<td>{{i.creation_date}}</td>
										<td>
											{{i.publishing_status}}
										</td>
										<td>
												<a href="javascript:;" class="ms-4"><i class="bx bx-message-square-edit "></i></a>
											</div>
                                    </div>
										</td>
									</tr>
								
									
								</tbody>
								{% endfor %}
							</table>
						</div>
					</div>
				</div>
	

			

				

			</div>
		</div>
		<!--end page wrapper -->
		<!--start overlay-->
		<div class="overlay toggle-icon"></div>
		<!--end overlay-->
		<!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
		<!--End Back To Top Button-->
		<footer class="page-footer">
			<p class="mb-0">Copyright © 2021. All right reserved.</p>
		</footer>
	</div>
	<!--end wrapper-->
	<!--start switcher-->
	<div class="switcher-wrapper">
		<div class="switcher-btn"> <i class='bx bx-cog bx-spin'></i>
		</div>
		<div class="switcher-body">
			<div class="d-flex align-items-center">
				<h5 class="mb-0 text-uppercase">Theme Customizer</h5>
				<button type="button" class="btn-close ms-auto close-switcher" aria-label="Close"></button>
			</div>
			<hr/>
			<p class="mb-0">Gaussian Texture</p>
			  <hr>
			  
			  <ul class="switcher">
				<li id="theme1"></li>
				<li id="theme2"></li>
				<li id="theme3"></li>
				<li id="theme4"></li>
				<li id="theme5"></li>
				<li id="theme6"></li>
			  </ul>
               <hr>
			  <p class="mb-0">Gradient Background</p>
			  <hr>
			  
			  <ul class="switcher">
				<li id="theme7"></li>
				<li id="theme8"></li>
				<li id="theme9"></li>
				<li id="theme10"></li>
				<li id="theme11"></li>
				<li id="theme12"></li>
				<li id="theme13"></li>
				<li id="theme14"></li>
				<li id="theme15"></li>
			  </ul>
		</div>
	</div>
	<!--end switcher-->
	<!-- Bootstrap JS -->
	<script src="{% static 'admini/assets/js/bootstrap.bundle.min.js' %}"></script>
	<!--plugins-->
	<script src="{% static 'admini/assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/simplebar/js/simplebar.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/metismenu/js/metisMenu.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/chartjs/js/Chart.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/vectormap/jquery-jvectormap-2.0.2.min.js' %}"></script>
    <script src="{% static 'admini/assets/plugins/vectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/jquery.easy-pie-chart/jquery.easypiechart.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/sparkline-charts/jquery.sparkline.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/jquery-knob/excanvas.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/jquery-knob/jquery.knob.js' %}"></script>
	  <script>
		  $(function() {
			  $(".knob").knob();
		  });
	  </script>
	  <script src="{% static 'admini/assets/js/index.js' %}"></script>
	<!--app JS-->
	<script src="{% static 'admini/assets/js/app.js' %}"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</body>

</html>

templates/bapp/user/header.html
{% load static %}
<header>
    <div class="topbar d-flex align-items-center">
        <nav class="navbar navbar-expand">
            <div class="topbar-logo-header">
                <div class="">
                    <img src="{% static 'admini/assets/images/logo-icon.png' %}" class="logo-icon" alt="logo icon">
                </div>
                <div class="">
                    <h4 class="logo-text">FirstBook </h4>
                </div>
            </div>
            <div class="mobile-toggle-menu"><i class='bx bx-menu'></i></div>
            <div class="search-bar flex-grow-1">
                <div class="position-relative search-bar-box">
                    <input type="text" class="form-control search-control" placeholder="Type to search..."> <span class="position-absolute top-50 search-show translate-middle-y"><i class='bx bx-search'></i></span>
                    <span class="position-absolute top-50 search-close translate-middle-y"><i class='bx bx-x'></i></span>
                </div>
            </div>
            <div class="top-menu ms-auto">
                <ul class="navbar-nav align-items-center">
                    <li class="nav-item mobile-search-icon">
                        <a class="nav-link" href="#">	<i class='bx bx-search'></i>
                        </a>
                    </li>
        
              
                 
                </ul>
            </div>
            <div class="user-box dropdown">
                <a class="d-flex align-items-center nav-link dropdown-toggle dropdown-toggle-nocaret" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'admini/assets/images/avatars/avatar-2.png' %}" class="user-img" alt="user avatar">
                    <div class="user-info ps-3">
                        <p class="user-name mb-0">Hello, {{ user.email }}!</p>
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  
                    <li><a class="dropdown-item" href="{% url 'bapp:homeview' %}"><i class="bx bx-user"></i><span>Orders</span></a>
                    </li>
               
             
                    <li>
                        <div class="dropdown-divider mb-0"></div>
                    </li>
                    <li><a class="dropdown-item" href="{% url 'bapp:logout' %}"><i class='bx bx-log-out-circle'></i><span>Logout</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<!--end header -->
<!--navigation-->
<div class="nav-container">
    <div class="mobile-topbar-header">
        <div>
            <img src="{% static 'admini/assets/images/logo-icon.png' %}" class="logo-icon" alt="logo icon">
        </div>
        <div>
            <h4 class="logo-text">title</h4>
        </div>
        <div class="toggle-icon ms-auto"><i class='bx bx-arrow-to-left'></i>
        </div>
    </div>
    <nav class="topbar-nav">
        <ul class="metismenu" id="menu">
            <li>
                <a href="{% url 'bapp:homeview' %}" class="has-arrow">
                    <div class="parent-icon"><i class='bx bx-home-circle'></i>
                    </div>
                    <div class="menu-title">Dashboard</div>
                </a>
              
            </li>
            <li>
                <a href="{% url 'bapp:booklist' %}" class="has-arrow">
                    <div class="parent-icon"><i class="bx  bx-line-chart"></i>
                    </div>
                    <div class="menu-title">Books</div>
                </a>
             
            </li>
    
            <li>
                <a class="has-arrow" href="{% url 'bapp:myservices' %}">
                    <div class="parent-icon"><i class='bx bx-message-square-edit'></i>
                    </div>
                    <div class="menu-title">My Services</div>
                </a>
            
            </li>


            <li>
                <a class="has-arrow" href="{% url 'bapp:servicelist' %}">
                    <div class="parent-icon icon-color-6"> <i class="bx bx-up-arrow-alt"></i>
                    </div>
                    <div class="menu-title">New Service</div>
                </a>
            
            </li>
      
        </ul>
    </nav>
</div>

templates/bapp/user/serviceorderconfirmation.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--favicon-->
	<link rel="icon" href="{% static 'admini/assets/images/favicon-32x32.png' %}" type="image/png" />
	<!--plugins-->
	<link href="{% static 'admini/assets/plugins/simplebar/css/simplebar.css' %}" rel="stylesheet" />
	<link href="{% static 'admini/assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet" />
	<link href="{% static 'admini/assets/plugins/metismenu/css/metisMenu.min.css' %}" rel="stylesheet" />
	<!-- loader-->
	<link href="{% static 'admini/assets/css/pace.min.css' %}" rel="stylesheet" />
	<script src="{% static 'admini/assets/js/pace.min.js' %}"></script>
	<!-- Bootstrap CSS -->
	<link href="{% static 'admini/assets/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
	<link href="{% static 'admini/assets/css/app.css' %}" rel="stylesheet">
	<link href="{% static 'admini/assets/css/icons.css' %}" rel="stylesheet">
	
	<title>Book App</title>
</head>

<body class="bg-theme bg-theme1">
	<!--wrapper-->
	<div class="wrapper">


		<div class="error-404 d-flex align-items-center justify-content-center">
			<div class="container">
				<div class="card py-5">
					<div class="row g-0">
						<div class="col col-xl-5">
							<div class="card-body p-4">
							<h2><span class="text-white">Purchase has been Completed !!!</span></h2>
							<h3 class="font-weight-bold">It's time to develop your book</h3>
                            <hr>
							<p>Service         : Writer </p>
							<p>Service Fee        :  50 </p>
							<p>Subscription start :  Start date </p>
							<p>Subscription End   : End date </p>
							<p>Subscription ID    : Subs ID </p>
							<p>Invoice ID         : txnid + date_of_txn +</p>
							<div class="mt-5"> <a href="{% url 'bapp:myservices' %}" class="btn btn-light btn-lg px-md-5 radius-30">Check</a>
									<a href="{% url 'bapp:homeview' %}" class="btn btn-light btn-lg ms-3 px-md-5 radius-30">Help</a>
								</div>
							</div>
						</div>
						<div class="col-xl-7">
							<img src="{% static 'admini/assets/images/completed.png' %}" class="img-fluid" alt="">
						</div>
					</div>
					<!--end row-->
				</div>
			</div>
		</div>

	</div>

    <footer class="page-footer">
        <p class="mb-0">Copyright © 2021. All right reserved.</p>
    </footer>
	<!--end wrapper-->
	<!--start switcher-->
	<div class="switcher-wrapper">
		<div class="switcher-btn"> <i class='bx bx-cog bx-spin'></i>
		</div>
		<div class="switcher-body">
			<div class="d-flex align-items-center">
				<h5 class="mb-0 text-uppercase">Theme Customizer</h5>
				<button type="button" class="btn-close ms-auto close-switcher" aria-label="Close"></button>
			</div>
			<hr/>
			<p class="mb-0">Gaussian Texture</p>
			  <hr>
			  
			  <ul class="switcher">
				<li id="theme1"></li>
				<li id="theme2"></li>
				<li id="theme3"></li>
				<li id="theme4"></li>
				<li id="theme5"></li>
				<li id="theme6"></li>
			  </ul>
               <hr>
			  <p class="mb-0">Gradient Background</p>
			  <hr>
			  
			  <ul class="switcher">
				<li id="theme7"></li>
				<li id="theme8"></li>
				<li id="theme9"></li>
				<li id="theme10"></li>
				<li id="theme11"></li>
				<li id="theme12"></li>
				<li id="theme13"></li>
				<li id="theme14"></li>
				<li id="theme15"></li>
			  </ul>
		</div>
	</div>
	<!--end switcher-->
	<!-- Bootstrap JS -->
	<script src="{% static 'admini/assets/js/bootstrap.bundle.min.js' %}"></script>
	<!--plugins-->
	<script src="{% static 'admini/assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/simplebar/js/simplebar.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/metismenu/js/metisMenu.min.js' %}"></script>
	<script src="{% static 'admini/assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js' %}"></script>
	<!--app JS-->
	<script src="{% static 'admini/assets/js/app.js' %}"></script>
</body>

</html>